#pragma once

#define SERVER_PHYSICS_TICKS_PER_SECOND 10.0
#define SERVER_PHYSICS_TICK (1.0 / SERVER_PHYSICS_TICKS_PER_SECOND)

#define SERVER_NET_TICKS_PER_SECOND 10.0
#define SERVER_NET_TICK (1.0 / SERVER_NET_TICKS_PER_SECOND)

#define CLIENT_NET_TICKS_PER_SECOND 24.0
#define CLIENT_NET_TICK (1.0 / CLIENT_NET_TICKS_PER_SECOND)

#define PACKET_HEADER_LEN (sizeof(int))